name: abhinav_tracking
description: Abhinav tracking app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  fl_chart: ^0.69.0
  url_launcher: ^6.2.5
  file_picker: ^10.3.7
  geolocator: ^10.1.1
  charts_flutter: ^0.12.0
  image_picker: ^1.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  photo_view: ^0.14.0
  intl: ^0.17.0
  shared_preferences: ^2.1.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true
